"""Build tests/fixtures/render_fixture_data.sql — a small, FK-consistent
subset of the live DB for deterministic render characterization tests.

Re-run only to intentionally change fixture coverage:
    PYTHONPATH=".venv/Lib/site-packages" PYTHONIOENCODING=utf-8 py scripts/build_render_fixture.py
Then REGEN the baselines (see plan Task 5):
    PYTHONPATH=".venv/Lib/site-packages" PYTHONIOENCODING=utf-8 REGEN=1 py -m pytest tests/test_render_chars.py -q

Output is data-only INSERTs (no schema): the test rebuilds the schema via
src.db.init_db + src.saeima.schema.init_saeima_tables/init_saeima_bills (which
also create the sqlite-vec vtabs and Saeima tables), then loads this SQL.

Path overrides (used when running from a git worktree where the live DB and
output tree live in different checkouts):
    ATMINA_FIXTURE_LIVE_DB  — path to the live source DB (default data/atmina.db)
    ATMINA_FIXTURE_OUT_SQL  — output .sql path (default tests/fixtures/render_fixture_data.sql)

Design: select a FIXED set of politician ids spanning multiple parties + an
organization slot + two journalists. The heavy, high-activity politicians carry
thousands of claims/votes each, so per-table caps bound the fixture size while
keeping every render code-path exercised (party cards, journalist/org profiles,
contradictions, Saeima vote/bill tables, X feed, dashboard counts). Determinism
comes from ORDER BY on every SELECT, fixed caps, and a fixed table order.
"""
import os
import sqlite3
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

LIVE_DB = os.environ.get("ATMINA_FIXTURE_LIVE_DB", "data/atmina.db")
OUT_SQL = Path(os.environ.get("ATMINA_FIXTURE_OUT_SQL",
                              "tests/fixtures/render_fixture_data.sql"))

# Fixed politician set — multi-party + organization (204) + journalists (57,182).
# 6=Dombrava(NA) 10=Kulbergs(AS) 15=Braže(JV) 26=Švinka(PRO) 30=Baško(MMN)
# 72=Indriksone(NA) 189=Pūce(LA) 182=Ozols(journ) 204=NBS(org) 57=Lapsa(journ)
FIXED_PIDS = [10, 72, 6, 15, 26, 189, 30, 182, 204, 57]

# Per-table caps — bound fixture size against high-activity politicians without
# losing render-path coverage. Contradiction-cited claims are always preserved
# (see step 3) and each kept claim's backing document is always included.
CLAIMS_PER_PID = 80        # recent claims (by id) authored about/by each pid
LINKED_DOCS_PER_PID = 40   # recent docs linked via junction but NOT claim-backing
IV_LIMIT = 1500            # recent individual Saeima votes (drives vote/bill chain)


def q(con, sql, params=()):
    return con.execute(sql, params).fetchall()


def emit_inserts(con, table, rows):
    """Yield deterministic INSERT statements for `rows` of `table`."""
    if not rows:
        return
    cols = [d[0] for d in con.execute(f"SELECT * FROM {table} LIMIT 0").description]
    collist = ", ".join(cols)
    for r in rows:
        vals = ", ".join(_lit(r[c]) for c in cols)
        yield f"INSERT INTO {table} ({collist}) VALUES ({vals});"


def _lit(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, bytes):
        return "X'" + v.hex() + "'"
    s = str(v).replace("'", "''")
    return f"'{s}'"


def main():
    con = sqlite3.connect(f"file:{LIVE_DB}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    ids = ",".join(str(p) for p in FIXED_PIDS)

    lines = [
        "-- AUTO-GENERATED by scripts/build_render_fixture.py — do not hand-edit.",
        "-- Data-only INSERTs; schema is built by src.db.init_db +",
        "-- src.saeima.schema.init_saeima_tables/init_saeima_bills in the test fixture.",
        "PRAGMA foreign_keys=OFF;",
        "BEGIN;",
    ]

    # 1. tracked_politicians (the anchor set)
    pol = q(con, f"SELECT * FROM tracked_politicians WHERE id IN ({ids}) ORDER BY id")
    lines += list(emit_inserts(con, "tracked_politicians", pol))

    # 2. parties referenced by those politicians (journalists/org have NULL party)
    parties = q(con, f"""
        SELECT * FROM parties WHERE name IN (
            SELECT DISTINCT party FROM tracked_politicians
            WHERE id IN ({ids}) AND party IS NOT NULL
        ) ORDER BY id
    """)
    lines += list(emit_inserts(con, "parties", parties))

    # 3. claims — recent CLAIMS_PER_PID per politician (subject OR speaker),
    #    plus any claim cited by a kept contradiction so the pretrunas page is
    #    FK-consistent. saeima_individual_votes carries the vote date; claims
    #    have no separate date filter needed (all current data is historical).
    claim_ids = set()
    for pid in FIXED_PIDS:
        rows = q(con, f"""
            SELECT id FROM claims
            WHERE opponent_id = ? OR speaker_id = ?
            ORDER BY id DESC LIMIT {CLAIMS_PER_PID}
        """, (pid, pid))
        claim_ids |= {r["id"] for r in rows}
    # contradiction-cited claims (old + new) for the set
    contras = q(con, f"SELECT * FROM contradictions WHERE opponent_id IN ({ids}) ORDER BY id")
    for c in contras:
        for k in ("claim_old_id", "claim_new_id"):
            if c[k] is not None:
                claim_ids.add(c[k])
    claims = []
    if claim_ids:
        cidlist = ",".join(str(c) for c in sorted(claim_ids))
        claims = q(con, f"SELECT * FROM claims WHERE id IN ({cidlist}) ORDER BY id")
    lines += list(emit_inserts(con, "claims", claims))
    claim_doc_ids = {r["document_id"] for r in claims if r["document_id"] is not None}

    # 4. documents — every backing doc of a kept claim (guarantees claim→doc FK),
    #    plus a capped slice of purely-linked docs per pid for news/X/profile tabs.
    doc_ids = set(claim_doc_ids)
    for pid in FIXED_PIDS:
        rows = q(con, f"""
            SELECT document_id FROM document_politicians
            WHERE politician_id = ?
            ORDER BY document_id DESC LIMIT {LINKED_DOCS_PER_PID}
        """, (pid,))
        doc_ids |= {r["document_id"] for r in rows}
    if doc_ids:
        idlist = ",".join(str(d) for d in sorted(doc_ids))
        docs = q(con, f"SELECT * FROM documents WHERE id IN ({idlist}) ORDER BY id")
        lines += list(emit_inserts(con, "documents", docs))
        dp = q(con, f"""
            SELECT * FROM document_politicians
            WHERE document_id IN ({idlist}) AND politician_id IN ({ids})
            ORDER BY document_id, politician_id, role
        """)
        lines += list(emit_inserts(con, "document_politicians", dp))

    # 5. contradictions for the set (already fetched in step 3)
    lines += list(emit_inserts(con, "contradictions", contras))

    # 6. analyses for the set
    analyses = q(con, f"SELECT * FROM analyses WHERE opponent_id IN ({ids}) ORDER BY id")
    lines += list(emit_inserts(con, "analyses", analyses))

    # 7. context_notes: set-owned + a few recent global briefs for blog/analizes
    notes = q(con, f"""
        SELECT * FROM context_notes
        WHERE opponent_id IN ({ids})
           OR id IN (
              SELECT id FROM context_notes
              WHERE note_type IN ('daily_brief','weekly_brief','synthesis')
              ORDER BY id DESC LIMIT 6
           )
        ORDER BY id
    """)
    lines += list(emit_inserts(con, "context_notes", notes))
    note_ids = {r["id"] for r in notes}

    # 8. brief_images for those notes
    if note_ids:
        nidlist = ",".join(str(n) for n in sorted(note_ids))
        imgs = q(con, f"SELECT * FROM brief_images WHERE note_id IN ({nidlist}) ORDER BY id")
        lines += list(emit_inserts(con, "brief_images", imgs))

    # 9. social_accounts + external_profiles for the set
    lines += list(emit_inserts(con, "social_accounts",
        q(con, f"SELECT * FROM social_accounts WHERE opponent_id IN ({ids}) ORDER BY id")))
    lines += list(emit_inserts(con, "external_profiles",
        q(con, f"SELECT * FROM external_profiles WHERE opponent_id IN ({ids}) ORDER BY id")))

    # 10. political_tensions involving the set (spriedzes page); cols are
    #     source_pid / target_pid (NOT *_politician_id).
    lines += list(emit_inserts(con, "political_tensions",
        q(con, f"""
            SELECT * FROM political_tensions
            WHERE source_pid IN ({ids}) OR target_pid IN ({ids})
            ORDER BY id
        """)))

    # 11. Saeima section. Two render needs, decoupled:
    #   (a) profile "balsojumi" tab → saeima_individual_votes for the set + their
    #       parent saeima_votes (motif/date).
    #   (b) global bills + laws pages and the profile "sponsored bills" tab →
    #       bills sponsored by the set UNION all bills carrying a base_law_slug
    #       (the laws page groups by slug). Recent iv mostly lack bill links, so
    #       bills are selected directly rather than derived from sampled votes.

    # (a) individual votes for the set
    iv = q(con, f"""
        SELECT * FROM saeima_individual_votes
        WHERE politician_id IN ({ids})
        ORDER BY id DESC LIMIT {IV_LIMIT}
    """)
    iv = sorted(iv, key=lambda r: r["id"])  # emit in ascending id order
    lines += list(emit_inserts(con, "saeima_individual_votes", iv))
    vote_ids = {r["vote_id"] for r in iv if r["vote_id"] is not None}

    # (b) bills: sponsored-by-set ∪ all base_law_slug bills
    bp_set = q(con, f"""
        SELECT * FROM saeima_bill_politicians WHERE politician_id IN ({ids})
        ORDER BY bill_id, politician_id, role, amendment_nr
    """)
    bill_ids = {r["bill_id"] for r in bp_set}
    bill_ids |= {r["id"] for r in q(con,
        "SELECT id FROM saeima_bills WHERE base_law_slug IS NOT NULL")}
    if bill_ids:
        blist = ",".join(str(b) for b in sorted(bill_ids))
        lines += list(emit_inserts(con, "saeima_bills",
            q(con, f"SELECT * FROM saeima_bills WHERE id IN ({blist}) ORDER BY id")))
        stages = q(con, f"SELECT * FROM saeima_bill_stages WHERE bill_id IN ({blist}) ORDER BY id")
        lines += list(emit_inserts(con, "saeima_bill_stages", stages))
        vote_ids |= {r["vote_id"] for r in stages if r["vote_id"] is not None}
        # bill_politicians restricted to included bills → every bill_id join resolves
        lines += list(emit_inserts(con, "saeima_bill_politicians",
            [r for r in bp_set if r["bill_id"] in bill_ids]))

    # (c) parent saeima_votes (iv-derived ∪ stage-referenced) + agenda + sessions
    if vote_ids:
        vlist = ",".join(str(v) for v in sorted(vote_ids))
        votes = q(con, f"SELECT * FROM saeima_votes WHERE id IN ({vlist}) ORDER BY id")
        agenda_ids = sorted({r["agenda_item_id"] for r in votes
                             if r["agenda_item_id"] is not None})
        if agenda_ids:
            alist = ",".join(str(a) for a in agenda_ids)
            agenda = q(con, f"SELECT * FROM saeima_agenda_items WHERE id IN ({alist}) ORDER BY id")
            sess_ids = sorted({r["session_db_id"] for r in agenda
                               if r["session_db_id"] is not None})
            if sess_ids:
                slist = ",".join(str(s) for s in sess_ids)
                lines += list(emit_inserts(con, "saeima_sessions",
                    q(con, f"SELECT * FROM saeima_sessions WHERE id IN ({slist}) ORDER BY id")))
            lines += list(emit_inserts(con, "saeima_agenda_items", agenda))
        lines += list(emit_inserts(con, "saeima_votes", votes))

    lines += ["COMMIT;", "PRAGMA foreign_keys=ON;", ""]

    OUT_SQL.parent.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_SQL} ({len(lines)} lines, {OUT_SQL.stat().st_size} bytes)")
    con.close()


if __name__ == "__main__":
    main()
